export const GET_FOTOS_FAM = "GET_FOTOS_FAM"
export const GET_FOTOS_FAM_OK = "GET_FOTOS_FAM_OK"
export const GET_FOTOS_FAM_FAIL = "GET_FOTOS_FAM_FAIL"

export const GET_FOTOS_COM = "GET_FOTOS_COM"
export const GET_FOTOS_COM_OK = "GET_FOTOS_COM_OK"
export const GET_FOTOS_COM_FAIL = "GET_FOTOS_COM_FAIL"

export const GET_FOTOS_INF = "GET_FOTOS_INF"
export const GET_FOTOS_INF_OK = "GET_FOTOS_INF_OK"
export const GET_FOTOS_INF_FAIL = "GET_FOTOS_INF_FAIL"

export const GET_FOTOS_PRIV = "GET_FOTOS_PRIV"
export const GET_FOTOS_PRIV_OK = "GET_FOTOS_PRIV_OK"
export const GET_FOTOS_PRIV_FAIL = "GET_FOTOS_PRIV_FAIL"

export const GET_FOTO_DET = "GET_FOTO_DET"
export const GET_FOTO_DET_OK = "GET_FOTO_DET_OK"
export const GET_FOTO_DET_FAIL = "GET_FOTO_DET_FAIL"

export const POST_FOTO_FAV = "POST_FOTO_FAV"
export const POST_FOTO_FAV_OK = "POST_FOTO_FAV_OK"
export const POST_FOTO_FAV_FAIL = "POST_FOTO_FAV_FAIL"

export const GET_FOTOS_FAVORITAS = "GET_FOTOS_FAVORITAS"
export const GET_FOTOS_FAVORITAS_OK = "GET_FOTOS_FAVORITAS_OK"
export const GET_FOTOS_FAVORITAS_FAIL = "GET_FOTOS_FAVORITAS_FAIL"

export const DELETE_FOTO_FAVORITAS = "DELETE_FOTO_FAVORITAS"
export const DELETE_FOTO_FAVORITAS_OK = "DELETE_FOTO_FAVORITAS_OK"
export const DELETE_FOTO_FAVORITAS_FAIL = "DELETE_FOTO_FAVORITAS_FAIL"

export const UPDATE_FOTO_FAVORITA = "UPDATE_FOTO_FAVORITA"
export const UPDATE_FOTO_FAVORITA_OK = "UPDATE_FOTO_FAVORITA_OK"
export const UPDATE_FOTO_FAVORITA_FAIL = "DUPDATE_FOTO_FAVORITA_FAIL"